name: Permissions Demo

on:
  push:

  workflow_dispatch:

permissions: {}

jobs:
  solo-lectura:
    runs-on: ubuntu-latest

    permissions: 
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Verificar que el checkout funcionó con solo read
        run: ls -lah
